@echo off
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\COCAINE\LGA\*" "https://datalakegltest.blob.core.windows.net/containertest/input/LGA_general_coc" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\COCAINE\SHA\*" "https://datalakegltest.blob.core.windows.net/containertest/input/SHA_general_coc" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\COCAINE\PR\*" "https://datalakegltest.blob.core.windows.net/containertest/input/PR_general_coc" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\COCAINE\SHOCK\*" "https://datalakegltest.blob.core.windows.net/containertest/input/SHOCK_general" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\OXYCODONE\LGA\*" "https://datalakegltest.blob.core.windows.net/containertest/input/LGA_general_oxy" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\OXYCODONE\SHA\*" "https://datalakegltest.blob.core.windows.net/containertest/input/SHA_general_oxy" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\OXYCODONE\PR\*" "https://datalakegltest.blob.core.windows.net/containertest/input/PR_general_oxy" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Cohort_Information\COCAINE\*" "https://datalakegltest.blob.core.windows.net/containertest/input/cohort_information/cocaine_cohort_information" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Cohort_Information\OXYCODONE\*" "https://datalakegltest.blob.core.windows.net/containertest/input/cohort_information/oxy_cohort_information" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Tail_Immersion\*" "https://datalakegltest.blob.core.windows.net/containertest/input/TI" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Von_Frey\*" "https://datalakegltest.blob.core.windows.net/containertest/input/VF" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Note\*" "https://datalakegltest.blob.core.windows.net/containertest/input/Note" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Irritability\*" "https://datalakegltest.blob.core.windows.net/containertest/input/IRR" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Old_Data_but_shock\COCAINE\*" "https://datalakegltest.blob.core.windows.net/containertest/input/OLD_SA_coc" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Old_Data_but_shock\OXYCODONE\*" "https://datalakegltest.blob.core.windows.net/containertest/input/OLD_SA_oxy" --recursive --overwrite=ifSourceNewer
azcopy copy "C:\Users\georg\George Lab Dropbox\George_Lab\Experiments\DataStream\DataSource\azure_excel_output_files\Old_Data_but_shock\old_SHOCK\*" "https://datalakegltest.blob.core.windows.net/containertest/input/SHOCK_sa" --recursive --overwrite=ifSourceNewer