DROP TABLE IF EXISTS Subject;

CREATE TABLE Subject (
    rfid integer PRIMARY KEY,
    rat VARCHAR (255),
    arrival_date DATE,
    brevital DATE,
    brevital_date DATE,
    brevital_done_by varchar(255),
    lga_15_date DATE,
    lga_16_date DATE,
    lga_17_date DATE,
    lga_18_date DATE,
    long_access_end_date DATE,
    long_access_start_date DATE,
    short_access_start_date DATE,
    short_access_end_date DATE,
    pre_shock_date DATE,
    shock_01_ma_date DATE,
    shock_02_ma_date DATE,
    shock_03_ma_date DATE,
    coat_color VARCHAR (255),
    date_of_birth DATE,
    date_of_eye_bleed DATE,
    date_of_ship DATE,
    date_of_wean DATE,
    dissection_date DATE,
    ear_punch VARCHAR (255),
    group_for_pre_shock VARCHAR (255),
    group_for_shock VARCHAR (255),
    handled_by VARCHAR (255),
    litter_number integer,
    litter_size integer,
    rack VARCHAR (255),
    recatheter_surgeon VARCHAR (255),
    recatheter_surgery_date DATE,
    shipping_box integer,
    surgeon VARCHAR (255),
    surgery_assist VARCHAR (255),
    surgery_date DATE,
    date_of_death DATE
)