DROP TABLE IF EXISTS von_frey;

CREATE TABLE von_frey (
    rfid                        bigint,
    subject                     varchar(255),
    cohort                      integer,
    sex                         varchar(255),
    experiment_group            varchar(255),
    drug                        varchar(255),
    vf1_right_force_1           float,
    vf1_right_force_2           float,
    vf1_right_force_3           float,
    vf1_right_force_avg         float,
    vf1_right_time_1            float,
    vf1_right_time_2            float,
    vf1_right_time_3            float,
    vf1_right_avg               float,
    vf1_left_force_1            float,
    vf1_left_force_2            float,
    vf1_left_force_3            float,
    vf1_left_force_avg          float,
    vf1_left_time_1             float,
    vf1_left_time_2             float,
    vf1_left_time_3             float,
    vf1_left_avg                float,
    von_frey_1_date             date,
    vf2_right_force_1           float,
    vf2_right_force_2           float,
    vf2_right_force_3           float,
    vf2_right_force_avg         float,
    vf2_right_time_1            float,
    vf2_right_time_2            float,
    vf2_right_time_3            float,
    vf2_right_avg               float,
    vf2_left_force_1            float,
    vf2_left_force_2            float,
    vf2_left_force_3            float,
    vf2_left_force_avg          float,
    vf2_left_time_1             float,
    vf2_left_time_2             float,
    vf2_left_time_3             float,
    vf2_left_avg                float,
    von_frey_2_date             date,
    von_frey_1_force            float,
    von_frey_1_time             float,
    von_frey_2_force            float,
    von_frey_2_time             float,
    von_frey_difference_force   float,
    constraint von_frey_pk
        primary key (rfid, cohort, experiment_group)
)