create table irritability
(
    subject           varchar(255),
    rfid              bigint,
    cohort            integer,
    sex               varchar(255),
    group             varchar(255),
    def_bsl_irr_1     NUMERIC,
    agg_bsl_irr_1     NUMERIC,
    irr_bsl_tot_1     NUMERIC,
    irr_bsl_scorer_1  varchar(255),
    def_bsl_irr_2     NUMERIC,
    agg_bsl_irr_2     NUMERIC,
    irr_bsl_total_2   NUMERIC,
    irr_bsl_scorer_2  varchar(255),
    def_bsl_irr_3     NUMERIC,
    agg_bsl_irr_3     NUMERIC,
    irr_bsl_total_3   NUMERIC,
    irr_bsl_scorer_3  varchar(255),
    def_bsl_ave       NUMERIC,
    agg_bsl_ave       NUMERIC,
    total_bsl_ave     NUMERIC,
    def_drug_irr_1    NUMERIC,
    agg_drug_irr_1    NUMERIC,
    irr_drug_tot_1    NUMERIC,
    irr_drug_scorer_1 varchar(255),
    def_drug_irr_2    NUMERIC,
    agg_drug_irr_2    NUMERIC,
    irr_drug_total_2  NUMERIC,
    irr_drug_scorer_2 varchar(255),
    def_drug_irr_3    NUMERIC,
    agg_drug_irr_3    NUMERIC,
    irr_drug_total_3  NUMERIC,
    irr_drug_scorer_3 varchar(255),
    def_drug_ave      NUMERIC,
    agg_drug_ave      NUMERIC,
    total_drug_ave    NUMERIC,
    diff_ave_def      NUMERIC,
    diff_ave_agg      NUMERIC,
    diff_ave_total    NUMERIC,
    constraint irritability_pk
        primary key (rfid)
);